export const GET_ERROR = "ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ALERT_ERROR = "GET_ALERT_ERROR";
export const CLEAR_ALERT_ERRORS = "CLEAR_ALERT_ERRORS";
export const SERVER_ERROR = "SERVER_ERROR";


export const TOGGLE = 'TOGGLE';
export const TOGGLE_FALSE = 'TOGGLE_FALSE';
export const CART_TOGGLE = 'CART_TOGGLE';
export const CART_TOGGLE_FALSE = 'CART_TOGGLE_FALSE';
export const TOP_SCROLL = 'TOP_SCROLL';



/** 
 * BIO STAR 
*/

export const BIO_STAR_LOGIN_TOKEN = 'BIO_STAR_LOGIN_TOKEN';
export const SCAN_FINGERPRINT_1 = 'SCAN_FINGERPRINT_1';
export const SCAN_FINGERPRINT_2 = 'SCAN_FINGERPRINT_2';
export const CLEAR_TEMPLATE = 'CLEAR_TEMPLATE';


/** 
 * LOGIN AUTH
*/

export const SET_CURRENT_USER = 'LOGIN_SUCCESS';
export const SIGNUP_DATA = 'SIGNUP_DATA';
export const CLEAR_SIGNUP_DATA = 'CLEAR_SIGNUP_DATA';
export const VERIFY_CODE = 'VERIFY_CODE';
export const LOGGED_USER = 'LOGGED_USER'
export const LOG_OUT = 'LOG_OUT'


/** 
 * CREATE SYSTEM ADMIN
*/

export const ADD_SYSTEM_ADMIN = 'ADD_SYSTEM_ADMIN';
export const UPDATE_SYSTEM_ADMIN = 'UPDATE_SYSTEM_ADMIN';
export const GET_SYSTEM_ADMIN = 'GET_SYSTEM_ADMIN';
export const GET_SYSTEM_YEAR = 'GET_SYSTEM_YEAR';

/** 
 * PACKAGES 
*/

export const ADD_PACKAGE = 'ADD_PACKAGE';
export const GET_PACKAGE = 'GET_PACKAGE';
export const GET_ACTIVE_PACKAGE = 'GET_ACTIVE_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const GET_PACKAGE_BY_ID = 'GET_PACKAGE_BY_ID'
export const GET_PACKAGE_BY_SALES_BRANCH = 'GET_PACKAGE_BY_SALES_BRANCH'


/**
 * PERIOD
*/

export const ADD_PERIOD = 'ADD_PERIOD';
export const GET_PERIOD = 'GET_PERIOD';
export const UPDATE_PERIOD = 'UPDATE_PERIOD';
export const GET_ACTIVE_PERIOD = 'GET_ACTIVE_PERIOD';




/**
 * BRANCH
*/

export const ADD_BRANCH = 'ADD_BRANCH';
export const GET_BRANCH = 'GET_BRANCH';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const GET_ACTIVE_BRANCH = 'GET_ACTIVE_BRANCH';


/**
 * DESIGNATION
*/

export const ADD_DESIGNATION = 'ADD_DESIGNATION';
export const GET_DESIGNATION = 'GET_DESIGNATION';
export const UPDATE_DESIGNATION = 'UPDATE_DESIGNATION';
export const GET_ACTIVE_DESIGNATION = 'GET_ACTIVE_DESIGNATION';
export const GET_FILTER_DESIGNATION = 'GET_FILTER_DESIGNATION';



/**
 * LOADER
*/

export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'


/**
 * EMPLOYEE
*/

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_ACTIVE_EMPLOYEE = 'GET_ACTIVE_EMPLOYEE';
export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID';
export const CLEAR_CURRENT_EMPLOYEE = 'CLEAR_CURRENT_EMPLOYEE';
export const UPDATE_EMPLOYEE_STATUS = 'UPDATE_EMPLOYEE_STATUS'
export const GET_ACTIVE_TRAINER = 'GET_ACTIVE_TRAINER';
export const GET_TRAINER_BY_BRANCH = 'GET_TRAINER_BY_BRANCH';


/**
 * MEMBER
*/

export const GET_MEMBER = 'GET_MEMBER';
export const GET_NEW_REGISTER_MEMBER_FILTER = 'GET_NEW_REGISTER_MEMBER_FILTER';
export const REGISTER_MEMBER = 'REGISTER_MEMBER'
export const GET_MEMBER_BY_ID = 'GET_MEMBER_BY_ID'
export const GET_ACTIVE_REGISTER_MEMBER_FILTER = 'GET_ACTIVE_REGISTER_MEMBER_FILTER'
export const GET_ACTIVE_STATUS_REGISTER_MEMBER_FILTER = 'GET_ACTIVE_STATUS_REGISTER_MEMBER_FILTER'
export const GET_ACTIVE_STATUS_NOT_EXPIRED_REGISTER_MEMBER_FILTER = 'GET_ACTIVE_STATUS_NOT_EXPIRED_REGISTER_MEMBER_FILTER'
export const GET_PENDING_REGISTER_MEMBER_FILTER = 'GET_PENDING_REGISTER_MEMBER_FILTER'
export const SET_CURRENT_UPDATE = 'SET_CURRENT_UPDATE'
export const CLEAR_CURRENT_UPDATE = 'CLEAR_CURRENT_UPDATE'
export const GET_EXPIRED_MEMBER = 'GET_EXPIRED_MEMBER'
export const GET_ACTIVE_MEMBER = 'GET_ACTIVE_MEMBER'
export const GET_CLASSES_MEMBER = 'GET_CLASSES_MEMBER'
export const GET_CPR = 'GET_CPR'
export const GET_MEMBER_ENTRANCE = 'GET_MEMBER_ENTRANCE'


/**
 * TRAINER FEES
*/

export const ADD_TRAINER_FEES = 'ADD_TRAINER_FEES';
export const GET_TRAINER_FEES = 'GET_TRAINER_FEES';
export const UPDATE_TRAINER_FEES = 'UPDATE_TRAINER_FEES';
export const GET_ACTIVE_TRAINER_FEES = 'GET_ACTIVE_TRAINER_FEES'
export const GET_PERIOD_OF_TRAINER = 'GET_PERIOD_OF_TRAINER'
export const GET_UNIQUE_TRAINER_BY_BRANCH = 'GET_UNIQUE_TRAINER_BY_BRANCH'



/**
 * CURRENCY
*/

export const ADD_CURRENCY = 'ADD_CURRENCY';
export const GET_CURRENCY = 'GET_CURRENCY';
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const DEFAULT_CURRENCY = 'DEFAULT_CURRENCY';




/**
 * DIET FOOD ITEM
*/

export const ADD_FOOD_ITEM = 'ADD_FOOD_ITEM';
export const GET_FOOD_ITEM = 'GET_FOOD_ITEM';
export const UPDATE_FOOD_ITEM = 'UPDATE_FOOD_ITEM';
export const GET_ACTIVE_FOOD_ITEM = 'GET_ACTIVE_FOOD_ITEM';



/**
 * DIET FOOD SESSION
*/

export const ADD_FOOD_SESSION = 'ADD_FOOD_SESSION';
export const GET_FOOD_SESSION = 'GET_FOOD_SESSION';
export const UPDATE_FOOD_SESSION = 'UPDATE_FOOD_SESSION';
export const GET_ACTIVE_FOOD_SESSION = 'GET_ACTIVE_FOOD_SESSION';



/**
 * MEMBER DIET
*/

export const GET_MEMBER_DIET_BY_DATE = 'GET_MEMBER_DIET_BY_DATE';
export const EMPTY_MEMBER_DIET_BY_DATE = 'EMPTY_MEMBER_DIET_BY_DATE'
export const GET_MEMBER_DIET_BY_DATE_FOR_TRAINER = 'GET_MEMBER_DIET_BY_DATE_FOR_TRAINER';
export const EMPTY_MEMBER_DIET_BY_DATE_FOR_TRAINER = 'EMPTY_MEMBER_DIET_BY_DATE_FOR_TRAINER'


/**
 * WORKOUTS
*/

export const ADD_WORKOUTS = 'ADD_WORKOUTS';
export const GET_WORKOUTS = 'GET_WORKOUTS';
export const UPDATE_WORKOUT_STATUS = 'UPDATE_WORKOUT_STATUS';
export const GET_ACTIVE_WORKOUTS = 'GET_ACTIVE_WORKOUTS';
export const GET_ACTIVE_WORKOUTS_BY_CATEGORY = 'GET_ACTIVE_WORKOUTS_BY_CATEGORY';



/**
 * WORKOUTS LEVEL
*/

export const ADD_WORKOUTS_LEVEL = 'ADD_WORKOUTS_LEVEL';
export const GET_WORKOUTS_LEVEL = 'GET_WORKOUTS_LEVEL';
export const GET_ACTIVE_WORKOUTS_LEVEL = 'GET_ACTIVE_WORKOUTS_LEVEL';
export const UPDATE_WORKOUT_LEVEL = 'UPDATE_WORKOUT_LEVEL';
export const UPDATE_WORKOUT_LEVEL_STATUS = 'UPDATE_WORKOUT_LEVEL_STATUS';



/**
 * MEMBER WORKOUT
*/

export const GET_MEMBER_WORKOUT_BY_DATE = 'GET_MEMBER_WORKOUT_BY_DATE';
export const EMPTY_MEMBER_WORKOUT_BY_DATE = 'EMPTY_MEMBER_WORKOUT_BY_DATE'
export const GET_MEMBER_WORKOUT_BY_DATE_FOR_TRAINER = 'GET_MEMBER_WORKOUT_BY_DATE_FOR_TRAINER';
export const EMPTY_MEMBER_WORKOUT_BY_DATE_FOR_TRAINER = 'EMPTY_MEMBER_WORKOUT_BY_DATE_FOR_TRAINER'


/**
 * TRAINER
*/

export const GET_MEMBERS_OF_TRAINER = 'GET_MEMBERS_OF_TRAINER';



/**
 * POINT OF SALES(STOCK)
 */

export const ADD_STOCK = 'ADD_STOCK'
export const GET_STOCK = 'GET_STOCK';
export const GET_ACTIVE_STOCK = 'GET_ACTIVE_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const GET_STOCK_BY_ID = 'GET_STOCK_BY_ID';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const GET_STOCK_SELL_BY_ID = 'GET_STOCK_SELL_BY_ID';



/**
 * POINT OF SALES(MEMBER)
 */

export const GET_CART_OF_MEMBER = 'GET_CART_OF_MEMBER';
export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const GET_CUSTOMER_ORDER_HISTORY = 'GET_CUSTOMER_ORDER_HISTORY';



/**
 * SHIFT
*/

export const ADD_SHIFT = 'ADD_SHIFT';
export const GET_SHIFT = 'GET_SHIFT';
export const GET_ACTIVE_SHIFT = 'GET_ACTIVE_SHIFT';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const GET_ACTIVE_SHIFT_BY_BRANCH = 'GET_ACTIVE_SHIFT_BY_BRANCH';
export const GET_NOT_EXPIRED_SHIFT_BY_BRANCH = 'GET_NOT_EXPIRED_SHIFT_BY_BRANCH';


/**
 * EMPLOYEE SHIFT
*/

export const ADD_EMPLOYEE_SHIFT = 'ADD_EMPLOYEE_SHIFT';
export const GET_EMPLOYEE_SHIFT = 'GET_EMPLOYEE_SHIFT';
export const UPDATE_EMPLOYEE_SHIFT = 'UPDATE_EMPLOYEE_SHIFT';
export const GET_EMPLOYEE_SHIFT_BY_ID_AND_BRANCH = 'GET_EMPLOYEE_SHIFT_BY_ID_AND_BRANCH';
export const GET_EMPLOYEE_SHIFT_BY_SHIFT_BRANCH_EMPLOYEE = 'GET_EMPLOYEE_SHIFT_BY_SHIFT_BRANCH_EMPLOYEE';


/**
 * ATTENDANCE
*/

export const GET_ATTENDANCE_DETAILS = 'GET_ATTENDANCE_DETAILS';
export const GET_MEMBER_ATTENDANCE_FILTER = 'GET_MEMBER_ATTENDANCE_FILTER';
export const GET_MEMBER_ATTENDANCE = 'GET_MEMBER_ATTENDANCE';
export const GET_MEMBER_ATTENDANCES = 'GET_MEMBER_ATTENDANCES';


/**
 * PRIVILEGE
 */

export const USER_BY_DESIGNATION_SEARCH = 'USER_BY_DESIGNATION_SEARCH'
export const ADD_ADMIN_PASSWORD = 'ADD_ADMIN_PASSWORD'
export const GET_ADMIN_PASSWORD = 'GET_ADMIN_PASSWORD'


/**
 * ROOM
*/

export const ADD_ROOM = 'ADD_ROOM';
export const GET_ROOM = 'GET_ROOM';
export const GET_ACTIVE_ROOM = 'GET_ACTIVE_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const GET_ROOM_BY_BRANCH = 'GET_ROOM_BY_BRANCH';



/**
 * CLASS
*/

export const ADD_CLASS = 'ADD_CLASS';
export const GET_CLASS = 'GET_CLASS';
export const GET_ACTIVE_CLASS = 'GET_ACTIVE_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const GET_CLASS_BY_BRANCH = 'GET_CLASS_BY_BRANCH';
export const GET_CLASS_BY_ID = 'GET_CLASS_BY_ID';
export const GET_CLASS_SCHEDULE_BY_DATE = 'GET_CLASS_SCHEDULE_BY_DATE';
export const GET_CUSTOMER_CLASS_SCHEDULE_BY_DATE = 'GET_CUSTOMER_CLASS_SCHEDULE_BY_DATE';
export const GET_CUSTOMER_CLASSES_DETAILS = 'GET_CUSTOMER_CLASSES_DETAILS';



/**
 * SUPPLIER
*/

export const GET_SUPPLIER = 'GET_SUPPLIER';
export const GET_ACTIVE_SUPPLIER = 'GET_ACTIVE_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const GET_SUPPLIER_BY_ID = 'GET_SUPPLIER_BY_ID';



/**
 * CONTRACT
*/

export const GET_CONTRACT = 'GET_CONTRACT';
export const GET_ACTIVE_CONTRACT = 'GET_ACTIVE_CONTRACT';
export const UPDATE_CONTRACT = 'UPDATE_CONTRACT';
export const GET_CONTRACT_BY_ID = 'GET_CONTRACT_BY_ID';



/**
 * ASSET
*/

export const GET_ASSET = 'GET_ASSET';
export const GET_ACTIVE_ASSET = 'GET_ACTIVE_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const GET_ASSET_BY_ID = 'GET_ASSET_BY_ID';
export const GET_ASSET_BY_SUPPLIER = 'GET_ASSET_BY_SUPPLIER';



/**
 * FEEDBACK
*/

export const GET_FEEDBACK = 'GET_FEEDBACK';
export const UPDATE_FEEDBACK = 'UPDATE_FEEDBACK';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const GET_FEEDBACK_MEMBER = 'GET_FEEDBACK_MEMBER';



/**
 * ANNOUNCEMENT
*/

export const GET_ANNOUNCEMENT = 'GET_ANNOUNCEMENT';
export const GET_ACTIVE_ANNOUNCEMENT = 'GET_ACTIVE_ANNOUNCEMENT';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';



/**
 * EVENT
*/

export const GET_EVENT = 'GET_EVENT';
export const GET_ACTIVE_EVENT = 'GET_ACTIVE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const ADD_EVENT = 'ADD_EVENT';
export const GET_EVENT_BY_DATE = 'GET_EVENT_BY_DATE';



/**
 * OFFER
*/

export const GET_OFFER = 'GET_OFFER';
export const GET_ACTIVE_OFFER = 'GET_ACTIVE_OFFER';
export const UPDATE_OFFER = 'UPDATE_OFFER';
export const ADD_OFFER = 'ADD_OFFER';




/**
 * GIFTCARD
*/

export const GET_GIFTCARD = 'GET_GIFTCARD';
export const GET_ACTIVE_GIFTCARD = 'GET_ACTIVE_GIFTCARD';
export const UPDATE_GIFTCARD = 'UPDATE_GIFTCARD';




/**
 * POLICY
*/

export const ADD_POLICY = 'ADD_POLICY';
export const GET_POLICY = 'GET_POLICY';
export const GET_ACTIVE_POLICY = 'GET_ACTIVE_POLICY';
export const UPDATE_POLICY = 'UPDATE_POLICY';

export const GET_MEMBER_TRANSACTION = 'GET_MEMBER_TRANSACTION';
export const GET_ALL_TRANSACTION = 'GET_ALL_TRANSACTION';
export const AMOUNT_BY_REDEEM_CODE = 'AMOUNT_BY_REDEEM_CODE';
export const GET_REFER_CODE = 'GET_REFER_CODE';




/**
 * ADMIN DASHBOARD
*/

export const GET_MEMBER_DASHBOARD = 'GET_MEMBER_DASHBOARD';
export const GET_PACKAGE_DISTRIBUTION = 'GET_PACKAGE_DISTRIBUTION';
export const GET_MOST_SELLING_STOCK = 'GET_MOST_SELLING_STOCK';
export const GET_BRANCH_SALES = 'GET_BRANCH_SALES';
export const GET_DASHBOARD_ATTENDANCE = 'GET_DASHBOARD_ATTENDANCE';
export const GET_REVENUE = 'GET_REVENUE';
export const GET_DASHBOARD_TOTALSALES = 'GET_DASHBOARD_TOTALSALES';
export const GET_PENDING_INSTALLMENTS = 'GET_PENDING_INSTALLMENTS';



/**
 * ADMIN DASHBOARD
*/

export const GET_PENDING_FREEZE = 'GET_PENDING_FREEZE';
export const GET_FREEZE_HISTORY = 'GET_FREEZE_HISTORY';



/**
 * NOTIFICATION
*/

export const GET_USER_NOTIFICATION = 'GET_USER_NOTIFICATION';
export const GET_USER_NOTIFICATIONS = 'GET_USER_NOTIFICATIONS';



/**
 * VAT
*/

export const ADD_VAT = 'ADD_VAT';
export const GET_VAT = 'GET_VAT';
export const UPDATE_VAT = 'UPDATE_VAT';
export const DEFAULT_VAT = 'DEFAULT_VAT';
export const GET_ACTIVE_VAT = 'GET_ACTIVE_VAT';




/**
 * REPORT
*/

export const GET_REPORT = 'GET_REPORT';
export const REMOVE_REPORT = 'REMOVE_REPORT';



/**
 * APPOINTMENT
*/

export const GET_APPOINTMENT_REQUESTS = 'GET_APPOINTMENT_REQUESTS';
export const GET_MEMBER_APPOINTMENT_HISTORY = 'GET_MEMBER_APPOINTMENT_HISTORY';
export const GET_MEMBER_APPOINTMENT_STATUS = 'GET_MEMBER_APPOINTMENT_STATUS';
export const GET_MEMBER_TRAFFIC = 'GET_MEMBER_TRAFFIC';



/**
 * MESSAGE
*/

export const GET_MESSAGE = 'GET_MESSAGE';




/**
 * BACKUP AND RESTORE
*/

export const GET_MANUAL_BACKUP = 'GET_MANUAL_BACKUP';
export const GET_RESTORE = 'GET_RESTORE';




/**
 * MONEY COLLECTION
*/

export const GET_MONEY_COLLECTION = 'GET_MONEY_COLLECTION';
export const GET_MONEY_COLLECTION_HISTORY = 'GET_MONEY_COLLECTION_HISTORY';
export const GET_MONEY_COLLECTION_BY_ID = 'GET_MONEY_COLLECTION_BY_ID';


/**
 * AUDIT_LOGS
*/

export const GET_AUDIT_LOGS = 'GET_AUDIT_LOGS';
export const VERIFY_ADMIN_PASSWORD = 'VERIFY_ADMIN_PASSWORD';


/**
 * INSTALLMENT
*/

export const GET_PACKAGE_INSTALLMENT = 'GET_PACKAGE_INSTALLMENT';
export const GET_TRAINER_INSTALLMENT = 'GET_TRAINER_INSTALLMENT';
